### ISSUE TITLE
Make release on npm, add install instructions

### ISSUE THREAD

**Issue by igorw** [nicokaiser/wamp.io#1]
Right now this is required to install the package:

```
{
    "dependencies": {
        "wamp.io": "git+https://github.com/nicokaiser/wamp.io"
    }
}
```

This should probably be documented in the README, or you could just release a package in the npm registry.

**Comment by nicokaiser** [comment]
Done :-) It's now in npm ('wamp.io').

**Comment by igorw** [comment]
Sweet, thanks!

**Comment by nevf** [comment]
Please add the npm install info to the readme. Thanks.
