### ISSUE TITLE
How to handle client conection problems?

### ISSUE THREAD

**Issue by yosva** [nicokaiser/wamp.io#17]
Trying to connect client.js example to a non running server do a Node.js crash. How can I handle connection problems? WebSocket object has an "On Error" event but can't see how to handle using publics Client or Session objects. By now my solutions is to hack Client code and add

``` javascript
 ws.on('error', function(error) {...})
```

to constructor. Is there a cleaner solution?

Thanks.

**Comment by nicokaiser** [comment]
The client code is just an example. I'm sure the original Autobahn.js WAMP code works better as client, and I'm sure that it has better error handling. This repository is a simple WAMP server.
