### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by Kenzku** [nicokaiser/wamp.io#2]
nom install does not work
It seems package.json has some problem.

Valid install targets:
npm ERR! ["0.1.1","0.1.2","0.1.4","0.1.5","0.1.6","0.2.0","0.2.1"]

**Comment by nicokaiser** [comment]
I upgraded the websocket.io version, so this should be fixed, can you test it again?

**Comment by Kenzku** [comment]
have you committed your changes?

**Comment by nicokaiser** [comment]
Now pushed.
