### ISSUE TITLE
New WebSocket Object does not return WAMP subprotocol?

### ISSUE THREAD

**Issue by Kenzku** [nicokaiser/wamp.io#5]
As the client side library, Autobahn.js have problems on connecting your example server. Thus, I tried the following comparison,
The first one will connect to Autobahn.js testing WAMP server, by running command:
more here: http://autobahn.ws/js/getstarted

``` bash
wstest -d -m wampserver -w ws://localhost:9000
```

Then, in Chrome console, I run:

``` javascript
var ws = new WebSocket("ws://localhost:9000",["wamp"])
```

then the _ws_ will be initialised:

``` JSON
WebSocket {binaryType: "blob", extensions: "", protocol: "wamp", onclose: null, onerror: null…}
```

**_As you can see that the protocol contains "wamp"**_

So I did the same thing on your example server (wamp.io/examples /pubsub/server.js)
either
corresponding to 

``` javascript
15 var ws = wsio.listen(9000);
```

``` javascript
var ws = new WebSocket("ws://localhost:9000",["wamp"])
```

or
corresponding to 

``` javascript
61 api.listen(9090);
```

``` javascript
var ws = new WebSocket("ws://localhost:9090",["wamp"])
```

but the different is the _ws_ giving no protocol:

``` JSON
WebSocket {binaryType: "blob", extensions: "", protocol: "", onclose: null, onerror: null…}
```

I also tried mine on top of express, which I asked you days ago,

``` javascript
...
var app = express();
var server = http.createServer(app);
var wamp = wampio.attach(wsio.attach(server));
app.configure(function(){
    app.set('port', process.env.PORT || 3000);
    ...
}
...
server.listen(app.get('port'), function(){
    console.log("Express server listening on port " + app.get('port'));
});
```

``` javascript
var ws_1 = new WebSocket("ws://localhost:3000",["wamp"])
```

but it returns the same _ws_ without protocol.

I think this might be the reason that AutoBahn.js cannot contact to. What do you think?
![Screen Shot 2013-03-05 at 12 53 54](https://f.cloud.github.com/assets/1387249/221008/1e74fe06-8586-11e2-89e4-d4c1d69e03f9.png)
(In the image, I changed your port to 8000 rather than 9000)

**Comment by nicokaiser** [comment]
You are right, the protocol should be returned as "wamp" by the server.

I updated the examples so they now use `ws` instead of `websocket.io`. Can you adapt this to your code and try again? I think the `ws` module handles the WebSocket protocol.

**Comment by Kenzku** [comment]
Yes, now it seems Autobahn.js can recognise your WAMP server. I just curious how does it attach to express server, since you change WebSocket.io to ws

**Comment by nicokaiser** [comment]
Good to know that `ws` supports the protocol header so it works with the Autobahn.js client!

I need to investigate how express works with `ws`.

**Comment by nicokaiser** [comment]
Can you try something like 

```
var WebSocketServer = require('ws').Server
  , express = require('express')
  , http = require('http')

var app = express();

var server = http.createServer(app);
var wss = new WebSocketServer({server:app});
var wamp = wampio.attach(wss);
app.configure(function(){
    app.set('port', process.env.PORT || 3000);
    ...
}
...
server.listen(app.get('port'), function(){
    console.log("Express server listening on port " + app.get('port'));
});
```

**Comment by Kenzku** [comment]
Probably, it doesn't work this way. I `console.log` the `app` and `server` to compare, then I found out `app` is not a server, but a request of `_events` of a server, but if bind to `server`, i.e. `var wss = new WebSocketServer({server:server});` the same problem appears again.

**Comment by nicokaiser** [comment]
This one works for me:

``` js
var WebSocketServer = require('ws').Server
  , express = require('express')
  , http = require('http')
  , wampio = require('wamp.io');

var app = express();

var server = http.createServer(app);
var wss = new WebSocketServer({server:server});
var wamp = wampio.attach(wss);
app.configure(function(){
    app.set('port', process.env.PORT || 3000);
});

server.listen(app.get('port'), function(){
    console.log("Express server listening on port " + app.get('port'));
});
```

**Comment by Kenzku** [comment]
You are right, this is what I tried before. I then found out I used the wrong version of `ws`, _0.4.20_, while you use, _~0.4.25_.

**Comment by teerytko** [comment]
Could this still be a problem on the examples? I tried to setup the server and client with the given examples and it fails on error on ws WebSocket 'server sent no subprotocol even though requested'?

**Comment by nicokaiser** [comment]
@teerytko The rpc example seems to work (although the client API is a bit strange, I know...). What client are you using?

**Comment by teerytko** [comment]
Yes, this was a problem with my client, which was node WebSocket library, it works differently from ws. So when I changed both sides to use ws then it works perfectly.
