### ISSUE TITLE
RPC message arguments

### ISSUE THREAD

**Issue by Kenzku** [nicokaiser/wamp.io#8]
It seems there is something not work with the WAMP specification, in `lib/handlers.js` (but I am not sure whether my understanding is correct or not)

``` Javascript
38 handlers[protocol.TYPE_ID_CALL] = function(client, args) {
39  callId = args.shift();
40  prefixes.resolveOrPass(procUri = args.shift());
41  args = args || [];
  ...
55  this.emit('call', procUri, args, cb);
56};
```

After line 41, the args will turn to an _array_ like _Object_, meaning the args looks like an array, but the type of it is an _Object_.
e.g. the RPC message argument in `[2,"4qK7nmQUsumUSGUM","calc:sum",[1,2,3,4,5]]` is `[1,2,3,4,5]`, but after your code _line 41_, it then changed to `[ [ 1, 2, 3, 4, 5 ] ]`

For more information, please check this screen shot.
![Screen Shot 2013-03-17 at 15 29 22](https://f.cloud.github.com/assets/1387249/268111/ed52e03c-8f07-11e2-8f23-2ddaa5ddd805.png)

**Comment by nicokaiser** [comment]
Well you can have more than one argument for the procedure call, so args must be an array.
